# permissions for end users to edit containersshes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: containerssh-editor-role
rules:
- apiGroups:
  - containerssh.patweber.de
  resources:
  - containersshes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - containerssh.patweber.de
  resources:
  - containersshes/status
  verbs:
  - get
