# permissions for end users to view containersshes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: containerssh-viewer-role
rules:
- apiGroups:
  - containerssh.patweber.de
  resources:
  - containersshes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - containerssh.patweber.de
  resources:
  - containersshes/status
  verbs:
  - get
